# Generated by Django 4.2.1 on 2023-06-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('authorName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(db_index=True)),
                ('member_id', models.IntegerField(db_index=True)),
                ('evaluate', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('images_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(db_index=True)),
                ('path', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('memberName', models.CharField(max_length=50)),
                ('memberAccount', models.CharField(max_length=50, unique=True)),
                ('memberPassword', models.CharField(max_length=30)),
                ('memberBirthday', models.DateField()),
                ('memberAge', models.IntegerField(default=0)),
                ('memberEmail', models.EmailField(max_length=254)),
                ('memberAddress', models.CharField(max_length=200, null=True)),
                ('memberPhone', models.CharField(max_length=15, null=True)),
                ('memberPoint', models.IntegerField(default=105)),
                ('memberTotalAmount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order_data',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField(db_index=True)),
                ('orderTime', models.DateTimeField()),
                ('orderDiscount', models.IntegerField(default=0)),
                ('orderDeliverFee', models.IntegerField(default=0)),
                ('orderAmount', models.IntegerField(default=0)),
                ('orderPayment', models.CharField(max_length=10)),
                ('orderName', models.CharField(max_length=50)),
                ('orderPhone', models.CharField(max_length=10)),
                ('orderAddress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order_product',
            fields=[
                ('orderProduct_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(db_index=True)),
                ('product_id', models.IntegerField(db_index=True)),
                ('orderProductQuantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=50)),
                ('author_id', models.IntegerField(db_index=True)),
                ('publisher_id', models.IntegerField(db_index=True)),
                ('productCategory', models.CharField(max_length=50)),
                ('productPrice', models.IntegerField(default=0)),
                ('productStock', models.IntegerField(default=0)),
                ('productLanguage', models.CharField(max_length=10)),
                ('productPublishDate', models.DateField()),
                ('productIntroduce', models.TextField(max_length=1000)),
                ('productSold', models.IntegerField(default=0)),
                ('productAgeLimit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('publisherName', models.CharField(max_length=50)),
            ],
        ),
    ]
